# https://travis-ci.org/#!/phlax/envoy-docs

dist: bionic

script:
  - git clone https://github.com/envoyproxy/envoy
  - cd envoy
  - ci/run_envoy_docker.sh 'ci/do_ci.sh docs'
  - ci/run_envoy_docker.sh 'ci/do_ci.sh docs'
  - ci/run_envoy_docker.sh 'ci/do_ci.sh docs'
