# https://travis-ci.org/#!/phlax/envoy-docs

dist: bionic

script:
  - export COMPOSE_FILE=./composition/docker-compose.yml
  - docker-compose pull envoy-docs
  - docker images
  - docker-compose run --rm envoy-docs
  - ls docs
