# https://travis-ci.org/#!/phlax/envoy-docs

dist: bionic

cache:
  directories:
    - /home/travis/build/phlax/envoy-docs/build

script:
  # - ls -alh build/tmp
  - export COMPOSE_FILE=./composition/docker-compose.yml
  - docker-compose pull envoy-docs
  - docker images
  - docker-compose run --rm envoy-docs
  - ls docs
