# https://travis-ci.org/#!/phlax/envoy-docs

dist: bionic

script:
  - git clone https://github.com/envoyproxy/envoy
  - cd envoy
  - docker pull envoyproxy/envoy-build-ubuntu:923df85a4ba7f30dcd0cb6b0c6d8d604f0e20f48
  - ci/run_envoy_docker.sh 'ci/do_ci.sh docs'
  - ci/run_envoy_docker.sh 'ci/do_ci.sh docs'
  - ci/run_envoy_docker.sh 'ci/do_ci.sh docs'

  - docker pull phlax/envoy-build
  - docker run --rm phlax/envoy-build
  - docker run --rm phlax/envoy-build
  - docker run --rm phlax/envoy-build
